In [23]:
import pandas as pd

# Read the CSV files into dataframes
final_nearby_places_df = pd.read_csv('final_nearby_places_df.csv')
final_sentiments_df = pd.read_csv('final_sentiments_dataframe.csv')

# Remove the word "County" from the 'county' column in final_nearby_places_df
final_nearby_places_df['County'] = final_nearby_places_df['County'].str.replace(' County', '')

master_df = pd.merge(final_nearby_places_df, final_sentiments_df, on='County', how='left')
master_df.drop('county', axis=1, inplace=True)

# Save the resultant dataframe to a new CSV file
master_df.to_csv('master_df.csv', index=False)

In [24]:
master_df.head(10)

,name,address,latitude,longitude,County,Grocery Stores,Food Outlets,Tourist Destinations,Hotels,Educational Institutions,...,Border Zone,Public Transportation,radius_miles,Competitor_Rating,Meijer_Rating,Meijer_Feedback_Useful,Meijer_Sentiment_Score,Meijer_Total_Review_Count,Meijer_Positive_Sentiment_Count,Meijer_Negative_Sentiment_Count
0,Kum & Go,"4800 44th St SW, Grandville, MI 49418, United ...",42.884595,-85.781344,Kent,0,5,0,0,0,...,0,0,1,NaN,2.56,92.0,-15.0,115.0,30.0,45.0
1,Kum & Go,"5437 Division Ave S, Wyoming, MI 49548, United...",42.865430,-85.664682,Kent,0,2,0,0,0,...,0,0,1,NaN,2.56,92.0,-15.0,115.0,30.0,45.0
2,Kum & Go,"4560 Chicago Dr SW, Grandville, MI 49418, Unit...",42.905083,-85.776313,Kent,0,6,0,1,1,...,0,0,1,NaN,2.56,92.0,-15.0,115.0,30.0,45.0
3,Kum & Go,"2134 Alpine Ave NW, Walker, MI 49544, United S...",43.002258,-85.688179,Kent,0,3,0,0,0,...,0,0,1,NaN,2.56,92.0,-15.0,115.0,30.0,45.0
4,Kum & Go,"5215 Kalamazoo Ave SE, Kentwood, MI 49508, Uni...",42.868823,-85.625761,Kent,0,1,0,0,0,...,0,0,1,NaN,2.56,92.0,-15.0,115.0,30.0,45.0
5,Casey's,"3781 M-140, Watervliet, MI 49098, United States",42.180177,-86.260869,Berrien,0,0,0,0,1,...,0,0,1,3.63,NaN,NaN,NaN,NaN,NaN,NaN
6,Casey's,"10299 Red Arrow Hwy, Bridgman, MI 49106, Unite...",41.931542,-86.569676,Berrien,0,0,0,0,1,...,0,0,1,3.63,NaN,NaN,NaN,NaN,NaN,NaN
7,Casey's,"714 Portage Street, Kalamazoo, MI 49001, Unite...",42.284556,-85.574704,Kalamazoo,0,19,2,0,2,...,0,0,1,3.45,2.28,67.0,-5.0,40.0,9.0,14.0
8,Casey's,"112 S State St, Freeport, MI 49325, United States",42.766097,-85.316561,Barry,0,0,0,0,0,...,0,0,1,3.81,NaN,NaN,NaN,NaN,NaN,NaN
9,Casey's,"10777 Karlin Rd, Buckley, MI 49620, United States",44.529429,-85.756948,Grand Traverse,0,0,0,0,0,...,0,0,1,3.93,NaN,NaN,NaN,NaN,NaN,NaN